# Copilot pre-install steps for ephemeral dev environment
# This file helps GitHub Copilot Agents install project dependencies
# before attempting builds/tests/lints, improving PR quality and speed.

steps:
  - name: macOS — Install Python and package manager
    if: runner.os == 'macOS'
    run: |
      brew update
      brew install python@3.13 || brew upgrade python@3.13
      python3 --version
      pip3 --version

  - name: macOS — Install documentation and linting tools
    if: runner.os == 'macOS'
    run: |
      brew install vale markdownlint-cli node
      vale --version || echo "Vale installation may need manual verification"
      markdownlint --version

  - name: macOS — Install optional security tools
    if: runner.os == 'macOS'
    run: |
      brew install ripgrep
      rg --version

  - name: Linux — Update package manager and install Python
    if: runner.os == 'Linux'
    run: |
      sudo apt-get update
      sudo apt-get install -y python3 python3-pip python3-venv curl wget git
      python3 --version
      pip3 --version

  - name: Linux — Install Node.js and documentation tools
    if: runner.os == 'Linux'
    run: |
      sudo apt-get install -y npm
      npm install -g markdownlint-cli
      markdownlint --version

  - name: Linux — Install Vale (optional documentation linter)
    if: runner.os == 'Linux'
    run: |
      set -euo pipefail
      TMP=$(mktemp -d)
      cd "$TMP"
      curl -sSL -o vale.tar.gz https://github.com/errata-ai/vale/releases/latest/download/vale_Linux_64-bit.tar.gz || exit 0
      tar -xzf vale.tar.gz || exit 0
      sudo mv vale /usr/local/bin/vale || true
      vale --version || true

  - name: Linux — Install ripgrep (optional performance tool)
    if: runner.os == 'Linux'
    run: |
      sudo apt-get install -y ripgrep || echo "ripgrep not available in apt, skipping"
      rg --version || echo "ripgrep not installed"

  - name: Install PyGuard Python dependencies
    run: |
      python3 -m pip install --upgrade pip setuptools wheel
      echo "Installing PyGuard in editable mode with development dependencies..."
      pip install -e ".[dev]" || echo "Failed to install package in editable mode"

  - name: Install pre-commit hooks (optional)
    run: |
      if command -v pre-commit &> /dev/null && [ -f ".pre-commit-config.yaml" ]; then
        echo "Installing pre-commit hooks..."
        pre-commit install || echo "pre-commit install failed"
      else
        echo "pre-commit not available or no config found, skipping"
      fi

  - name: Verify PyGuard installation
    run: |
      python3 -c "import pyguard; print(f'PyGuard version: {pyguard.__version__}')" || echo "PyGuard not yet installed"
      pyguard --version || echo "PyGuard CLI not yet available"

  - name: Confirm development environment
    run: |
      echo "=== Python Environment ==="
      echo "Python: $(python3 --version 2>/dev/null || echo missing)"
      echo "pip: $(pip3 --version 2>/dev/null | head -1 || echo missing)"
      echo "venv: $(python3 -m venv --help > /dev/null 2>&1 && echo available || echo missing)"
      echo ""
      echo "=== Code Quality Tools ==="
      echo "black: $(black --version 2>/dev/null | head -1 || echo missing)"
      echo "ruff: $(ruff --version 2>/dev/null || echo missing)"
      echo "pylint: $(pylint --version 2>/dev/null | head -1 || echo missing)"
      echo "mypy: $(mypy --version 2>/dev/null || echo missing)"
      echo "pytest: $(pytest --version 2>/dev/null | head -1 || echo missing)"
      echo "bandit: $(bandit --version 2>/dev/null || echo missing)"
      echo ""
      echo "=== Documentation & Linting Tools ==="
      echo "markdownlint: $(markdownlint --version 2>/dev/null || echo missing)"
      echo "Vale: $(vale --version 2>/dev/null || echo missing)"
      echo ""
      echo "=== Optional Performance Tools ==="
      echo "ripgrep: $(rg --version 2>/dev/null | head -1 || echo missing)"
      echo "PyGuard: $(pyguard --version 2>/dev/null || echo 'not yet installed')"
