# Pre-commit hooks for PyGuard repository
# Install: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # PyGuard dogfooding - use PyGuard to scan itself
  - repo: local
    hooks:
      - id: pyguard-self-check
        name: PyGuard Security Self-Check
        entry: pyguard
        language: python
        types: [python]
        args: ['--security-only', '--scan-only', '--no-html']
        pass_filenames: true
        additional_dependencies: []

  # Code formatting
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3.13

  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ['--profile', 'black']

  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: '1.8.6'
    hooks:
      - id: bandit
        args: ['-c', '.bandit', '-r', 'pyguard/']
        exclude: ^tests/

  # Secret detection
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks

  # Pre-commit standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']  # Allow custom YAML tags
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-ast  # Python syntax check
      - id: debug-statements  # Check for debugger imports

  # Python type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: ['--ignore-missing-imports', '--no-strict-optional']
        exclude: ^(tests|benchmarks|examples)/

  # YAML linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: ['-c', '.yamllint.yml']
        files: \.(yaml|yml)$

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: ['--config', '.markdownlint.json']
        files: \.md$
        exclude: ^(PYTEST_|RIPGREP_|COVERAGE_|TEST_|\.github/)

# Configuration for CI
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: 'main'
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [pyguard-self-check]  # Skip local hooks in CI
  submodules: false
