name: Setup Python with PyGuard Dependencies
description: Sets up Python with caching and installs PyGuard dependencies
inputs:
  python-version:
    description: Python version to use
    required: false
    default: '3.13'
  install-dev:
    description: Install development dependencies
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          pyproject.toml
          setup.py

    - name: Install dependencies
      shell: bash
      run: |
        set -euo pipefail
        python -m pip install --upgrade pip setuptools wheel
        if [ "${{ inputs.install-dev }}" = "true" ]; then
          pip install -e ".[dev]"
        else
          pip install -e .
        fi
