name: Performance Benchmarks

on:
  # Only run on schedule or manual trigger - benchmarks are expensive
  schedule:
    # Run benchmarks weekly on Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false  # Let benchmarks complete

defaults:
  run:
    shell: bash

jobs:
  benchmark:
    name: Run Performance Benchmarks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 1

    - name: Setup Python and dependencies
      uses: ./.github/actions/setup-python
      with:
        python-version: '3.13'
        install-dev: 'true'

    - name: Run security benchmarks
      shell: bash
      run: |
        set -euo pipefail
        python benchmarks/bench_security.py | tee benchmark-results.txt
      continue-on-error: true

    - name: Store benchmark results
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: benchmark-results
        path: benchmark-results.txt
        retention-days: 90
      if: always()

    - name: Add benchmark summary
      if: always()
      shell: bash
      run: |
        {
          echo "## ⚡ Performance Benchmark Results"
          echo ""
          echo '```'
          cat benchmark-results.txt || echo "No results file found"
          echo '```'
          echo ""
          echo "_Benchmarks run weekly to track performance trends_"
        } >> "${GITHUB_STEP_SUMMARY}"
