name: PyGuard Incremental Scan

on:
  pull_request:
    paths:
      - '**.py'

permissions:
  contents: read
  security-events: write

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install RipGrep
        run: |
          curl -LO https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep_14.1.0-1_amd64.deb
          sudo dpkg -i ripgrep_14.1.0-1_amd64.deb

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.11'

      - name: Install PyGuard
        run: |
          pip install -e .

      - name: Find changed Python files
        id: changed-files
        run: |
          git diff origin/${{ github.base_ref }}...HEAD --name-only | \
            rg "\.py$" > changed_files.txt || true

          echo "count=$(wc -l < changed_files.txt | tr -d ' ')" >> $GITHUB_OUTPUT

      - name: Scan changed files only
        if: steps.changed-files.outputs.count > 0
        run: |
          cat changed_files.txt | xargs pyguard --scan-only --sarif --no-html

      - name: Upload SARIF
        if: steps.changed-files.outputs.count > 0
        uses: github/codeql-action/upload-sarif@f443b600d91635bebf5b0d9ebc620189c0d6fba5 # v4.30.8
        with:
          sarif_file: pyguard-report.sarif
